# Site settings
title: CSS Wizardry
email: csswizardry@gmail.com
description: "CSS Architecture, Web Performance Optimisation, and more, by Harry Roberts"
baseurl: ""
url: "https://csswizardry.com"
future: true
cloudinary: "https://res.cloudinary.com/csswizardry/image/fetch/f_auto,q_auto/https://csswizardry.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 10

# Gems
gems: [jekyll-paginate]
